'@Ignore - only unignore to test compiler works
'@TestSuite [DGNT] Duplicate Group Name Tests

namespace Tests.AfterEachNotRunning
  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  '@It group1
  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  '@Test simple
  function group1_test()
    m.assertTrue(true)
  end function

  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  '@It group2
  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  '@Test simple
  function group2_test()
    m.assertTrue(true)
  end function


  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  '@It group2
  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  '@Test simple
  function group2_dupe_test()
    m.assertTrue(true)
  end function


  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  '@It group3
  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  '@Test simple
  function group3_test()
    m.assertTrue(true)
  end function

  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  '@It group1
  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  '@Test simple
  function group1_dupe_test()
    m.assertTrue(true)
  end function
end namespace