'@Ignore - only unignore to test compiler works - remove REMOVE_THIS to test
'@TestSuite [RBSA] REMOVE_THIS Rooibos before after tests
namespace Tests.DuplicateGroupNames

  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  '@It tests before each and after each are running
  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  '@BeforeEach
  function beforeEach() as void
    ? "!!! Before"
  end function


  '@AfterEach
  function afterEach() as void
    ? "!!! After"
  end function

  '@Test before after
  function before_after() as void

    assertResult = m.Fail("reason")

    isFail = m.currentResult.isFail
    m.currentResult.Reset()

    m.assertFalse(assertResult)
    m.assertTrue(isFail)
  end function

end namespace