

namespace Tests

  @Ignore("only unignore to test compiler works")
  @TestSuite
  class AfterEachNotRunning extends Rooibos.BaseTestSuite
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @It("group1")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    @Test("simple")
    function group1_test()
      m.assertTrue(true)
    end function

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @It("group2")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    @Test("simple")
    function group2_test()
      m.assertTrue(true)
    end function


    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @It("group22")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    '@beforeEach

    @Test("simple2")
    function group2_dupe_test()
      m.assertTrue(true)
    end function


    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @It("group3")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    @Test("simple")
    function group3_test()
      m.assertTrue(true)
    end function

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @It("group11")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    @Test("simple")
    function group1_dupe_test()
      m.assertTrue(true)
    end function

    @Test("simple2")
    function group1_dupe_test2()
      m.assertTrue(true)
    end function
  end class
end namespace