namespace Tests

  @Ignore("only unignore to test compiler works - remove REMOVE_THIS to test")
  @TestSuite
  class DuplicateGroupNames extends Rooibos.BaseTestSuite 
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @It("tests before each and after each are running")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    @BeforeEach
    override function group_beforeEach() as void
      ? "!!! Before"
    end function


    @AfterEach
    override function group_afterEach() as void
      ? "!!! After"
    end function

    @Test
    function before_after() as void

      assertResult = m.Fail("reason")

      isFail = m.currentResult.isFail
      m.currentResult.Reset()

      m.assertFalse(assertResult)
      m.assertTrue(isFail)
    end function

  end class
end namespace