function hitAllStatements() as dynamic
  loopCount = 0
  for i = 0 to 10
      loopCount++
  end for

  tryAgain:
  if loopCount = 11 
      loopCount++
      goto tryAgain
  else if loopCount = 12 
      loopCount++
      goto tryAgain
  else
      loopCount++
  end if

  while loopCount > 0
      loopCount--
      if loopCount = 1 
          exit while
      end if
  end while

  obj = {
      one: 1
  }
  obj["two"] = 2
  obj.three = 3

  for each key in obj
      print obj[key]
  end for

  return false
end function