'@TestSuite [BEAER] BeforeEach and AfterEach Running
namespace Rooibos.Tests.VeritfyBeforeEachAfterEach

  '@Setup
  function Setup() as void
    ? "!!! Setup"
  end function


  '@TearDown
  function TearDown() as void
    ? "!!! TearDown"
  end function

  '@BeforeEach
  function BeforeEach() as void
    ? "!!! Before"
  end function


  '@AfterEach
  function AfterEach() as void
    ? "!!! After"
  end function

  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  '@It tests group 1 - should have global before/after 
  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  '@Test 1 
  function group1_1() as void
    m.assertTrue(true)
  end function

  '@Test 2
  function group1_2() as void
    m.assertTrue(true)
  end function

  '@Test 3
  '@Params["a"]
  '@Params["b"]
  '@Params["c"]
  function group1_3(values) as void
    m.assertTrue(true)
  end function

  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  '@It tests group 2 - should have group before after
  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  '@BeforeEach
  function group2_BeforeEach() as void
    ? "!!! Before GROUP 2"
  end function


  '@AfterEach
  function group2_AfterEach() as void
    ? "!!! After GROUP 2"
  end function

  '@Test 1 
  function group2_1() as void
    m.assertTrue(true)
  end function

  '@Test 2
  function group2_2() as void
    m.assertTrue(true)
  end function

  '@Test 3
  '@Params["a"]
  '@Params["b"]
  '@Params["c"]
  function group2_3(values) as void
    m.assertTrue(true)
  end function

  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  '@It tests group 3 - should have global before/after
  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  '@Test 1 
  function group3_1() as void
    m.assertTrue(true)
  end function

  '@Test 2
  function group3_2() as void
    m.assertTrue(true)
  end function

  '@Test 3
  '@Params["a"]
  '@Params["b"]
  '@Params["c"]
  function group3_3(values) as void
    m.assertTrue(true)
  end function
end namespace
