namespace tests

  @noEarlyExit
  @suite("Rooibos assertion tests")
  class AssertionTests extends rooibos.BaseTestSuite

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @describe("tests basic assertions")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    @it("Fail")
    function _()

      m.Fail("reason")

      isFail = m.currentResult.isFail
      m.currentResult.Reset()


      m.assertTrue(isFail)
    end function

    @it("FailCrash")
    function _()

      try
        ' this will cause exception on purpose
        result = 2 / 0
        print result
      catch e
        m.failCrash(e)
      end try

      isFail = m.currentResult.isFail
      isCrash = m.currentResult.isCrash
      m.currentResult.Reset()

      m.assertTrue(isCrash)
      m.assertTrue(isFail)
    end function

    @it("AssertTrue")
    @params(true, true)
    @params(false, false)
    @params(invalid, false)
    @params(0, false)
    @params(1, false)
    @params("test", false)
    function _(value, expectedAssertResult)

      m.assertTrue(value)
      isFail = m.currentResult.isFail
      m.currentResult.Reset()


      m.assertEqual(isFail, not expectedAssertResult)
    end function


    @it("AssertFalse")
    @params(false, true)
    @params(true, false)
    @params(invalid, false)
    @params(0, false)
    @params(1, false)
    @params("test", false)
    function _(value, expectedAssertResult)

      m.assertFalse(value)

      isFail = m.currentResult.isFail
      m.currentResult.Reset()


      m.assertEqual(isFail, not expectedAssertResult)
    end function

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @describe("tests AssertArrayContainsAAs")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    @it("Fail")
    @params([{"one": 1}], [{"one": 2}])
    @params([{"one": 1}], [{"one": "a"}])
    @params([{"one": 1}], [{}])
    @params([{"one": 1}], [invalid])
    @params([{"one": 1}], [])
    @params([{"one": 1}], invalid)
    @params([{"one": 1}], [[]])
    @params([{"one": 1}], ["wrong"])
    @params([{"one": 1}], [2])
    @params([{"one": "a"}], [{"one": 1}])
    @params([{"two": 1}], [{"one": 1}])
    @params([invalid], [{"one": 1}])
    @params(invalid, [{"one": 1}])
    @params([{"one": 1, "two": 2}], [{"one": "1"}])
    @params([{"one": 1}, {"two": 2}], [{"one": "1"}, {"two": "a"}])
    @params([{"one": 1}, {"two": 2}], [{"a": 1}, {"a": 1}, {"a": 1}])
    function _(expectedAAs, items)

      m.assertArrayContainsAAs(items, expectedAAs)

      isFail = m.currentResult.isFail
      m.currentResult.Reset()


      m.assertTrue(isFail)
    end function


    @it("pass")
    @params([], [])
    @params([{}], [{}])
    @params([{"one": 1}], [{"one": 1}])
    @params([{"one": 1, "two": 2}], [{"one": 1, "two": 2}])
    @params([{"one": 1, "two": 2}], [{"two": 2, "one": 1}])
    @params([{"one": 1, "two": 2}, {"one": 1}], [{"one": 1}, {"two": 2, "one": 1}])
    @params([{"one": 1, "two": 2}, {"one": 1}, {"three": 3}], [{"one": 1}, {"three": 3}, {"two": 2, "one": 1}])
    function _(expectedAAs, items)

      m.assertArrayContainsAAs(items, expectedAAs)

      isFail = m.currentResult.isFail

      m.currentResult.Reset()

      m.assertFalse(isFail)
    end function

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @describe("tests global is present on testSuite")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    @beforeEach
    function test_assertGlobal_beforeEach()
      m.beforeEachGlobal = m.global
    end function

    @afterEach
    function test_assertGlobal_afterEach()
      m.afterEachGlobal = m.global
    end function

    @it("global is in test")
    function _()
      m.assertNotInvalid(m.global)
    end function

    @it("global is in before each and after each")
    function _()
      m.assertNotInvalid(m.global)
      m.assertNotInvalid(m.beforeEachGlobal)
      m.assertNotInvalid(m.afterEachGlobal)
    end function

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @describe("tests AssertArrayContainsOnlyValuesOfType")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    @it("pass")
    @params(["one", "two", "three"], "String")
    @params([1, 2, 3], "Integer")
    @params([true, true, false], "Boolean")
    @params([[true, true], [false, false]], "Array")
    @params([{"test": 1}, {"test": 1}], "AssociativeArray")
    function _(values, typeName)

      m.assertArrayContainsOnlyValuesOfType(values, typeName)
      isFail = m.currentResult.isFail

      m.currentResult.Reset()

      m.assertFalse(isFail)

    end function

    @it("fail")
    @params(["one", 2, "three"], "String")
    @params([1, "two", 3], "Integer")
    @params([true, "true", false], "Boolean")
    @params([[true, true], false, false], "Array")
    @params([{"test": 1}, "notAA"], "AssociativeArray")
    @params(["one", "two", "three"], "UnknownType")
    @params(["one", "two", "three"], "Integer")
    @params([1, 2, 3], "String")
    @params([true, true, false], "String")
    @params([[true, true], [false, false]], "AssociativeArray")
    @params([{"test": 1}, {"test": 1}], "Array")
    function _(values, typeName)

      m.assertArrayContainsOnlyValuesOfType(values, typeName)
      isFail = m.currentResult.isFail
      m.currentResult.Reset()


      m.assertTrue(isFail)


    end function

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @describe("tests AssertNotEmpty")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    @it("pass")
    @params(["one", "two", "three"])
    @params([1, 2, 3])
    @params([true])
    @params([[true, true], [false, false]])
    @params([{"test": 1}])
    @params("not empty")
    @params([invalid])
    function _(values)

      m.assertNotEmpty(values)
      isFail = m.currentResult.isFail

      m.currentResult.Reset()

      m.assertFalse(isFail)

    end function

    @it("fail")
    @params(invalid)
    @params([])
    @params({})
    @params(1)
    @params("")
    function _(values)

      m.assertNotEmpty(values)
      isFail = m.currentResult.isFail

      m.currentResult.Reset()

      m.assertTrue(isFail)

    end function

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @describe("tests AssertEmpty")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    @it("pass")
    @params([])
    @params({})
    @params("")
    function _(values)

      m.assertEmpty(values)
      isFail = m.currentResult.isFail

      m.currentResult.Reset()

      m.assertFalse(isFail)

    end function

    @it("fail")
    @params(1)
    @params(invalid)
    @params(["one", "two", "three"])
    @params([1, 2, 3])
    @params([true])
    @params([[true, true], [false, false]])
    @params([{"test": 1}])
    @params("not empty")
    @params([invalid])
    function _(values)

      m.assertEmpty(values)
      isFail = m.currentResult.isFail

      m.currentResult.Reset()

      m.assertTrue(isFail)

    end function

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @describe("tests expect")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    @it("multi return values")
    function _()
      obj = {}
      m.expect(obj, "mockMethod", 5, invalid, {"multiResult": ["one", 2, invalid, "last"]}, true)

      result = obj.mockMethod()
      m.assertEqual(result, "one")

      result = obj.mockMethod()
      m.assertEqual(result, 2)

      result = obj.mockMethod()
      m.assertEqual(result, invalid)

      result = obj.mockMethod()
      m.assertEqual(result, "last")

      result = obj.mockMethod()
      m.assertEqual(result, "last")

      m.assertMocks()
      isFail = m.currentResult.isFail

      m.currentResult.Reset()
      m.assertFalse(isFail)

    end function

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @describe("tests expect with overloaded expectOnce")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    @it("simple test")
    function _()
      obj = {}
      arg1 = "arg1"
      arg2 = "arg2"
      arg3 = "arg3"
      result1 = 1
      result2 = 2
      result3 = 3

      m.expectOnce(obj, "mockMethod", [arg1], result1, true)
      m.expectOnce(obj, "mockMethod", [arg2], result2, true)
      m.expectOnce(obj, "mockMethod", [arg3], result3, true)

      result = obj.mockMethod(arg1)
      m.assertEqual(result, result1)

      result = obj.mockMethod(arg2)
      m.assertEqual(result, result2)

      result = obj.mockMethod(arg3)
      m.assertEqual(result, result3)

      m.assertMocks()
      isFail = m.currentResult.isFail

      m.currentResult.Reset()
      m.assertFalse(isFail)
    end function


    @it("can set up multi expects on same method - one invocation with any args")
    function _()
      obj = {}
      arg1 = "arg1"
      ' not used arg2 = "arg2"
      arg3 = "arg3"
      result1 = 1
      result2 = 2
      result3 = 3

      m.expectOnce(obj, "mockMethod", [arg1], result1, true)
      m.expectOnce(obj, "mockMethod", invalid, result2, true)
      m.expectOnce(obj, "mockMethod", [arg3], result3, true)

      result = obj.mockMethod(arg1)
      m.assertEqual(result, result1)

      result = obj.mockMethod("do not care about args", "used in invocation", 2)
      m.assertEqual(result, result2)

      result = obj.mockMethod(arg3)
      m.assertEqual(result, result3)

      m.assertMocks()
      isFail = m.currentResult.isFail

      m.currentResult.Reset()
      m.assertFalse(isFail)

    end function

    @it("can set up multi expects on same method - multi params")
    function _()
      obj = {}
      arg1 = "arg1"
      arg2 = "arg2"
      arg3 = "arg3"
      result1 = 1
      result2 = 2
      result3 = 3

      m.expectOnce(obj, "mockMethod", [arg1, arg2, arg3], result1, true)
      m.expectOnce(obj, "mockMethod", [arg2, arg3, arg1], result2, true)
      m.expectOnce(obj, "mockMethod", [arg3, arg2, arg1], result3, true)

      result = obj.mockMethod(arg1, arg2, arg3)
      m.assertEqual(result, result1)

      result = obj.mockMethod(arg2, arg3, arg1)
      m.assertEqual(result, result2)

      result = obj.mockMethod(arg3, arg2, arg1)
      m.assertEqual(result, result3)

      m.assertMocks()
      isFail = m.currentResult.isFail

      m.currentResult.Reset()
      m.assertFalse(isFail)

    end function

    @it("multi test, multi params with other expects")
    function _()
      obj = {}
      arg1 = "arg1"
      arg2 = "arg2"
      arg3 = "arg3"
      result1 = 1
      result2 = 2
      result3 = 3

      m.expectOnce(obj, "anotherMockMethod", invalid, "another", true)
      m.expectOnce(obj, "anotherMockMethod2", [1, 2, 3], "another2", true)
      m.expectOnce(obj, "mockMethod", [arg1, arg2, arg3], result1, true)
      m.expectOnce(obj, "mockMethod", [arg2, arg3, arg1], result2, true)
      m.expectOnce(obj, "mockMethod", [arg3, arg2, arg1], result3, true)

      result = obj.anotherMockMethod()
      m.assertEqual(result, "another")

      result = obj.anotherMockMethod2(1, 2, 3)
      m.assertEqual(result, "another2")

      result = obj.mockMethod(arg1, arg2, arg3)
      m.assertEqual(result, result)

      result = obj.mockMethod(arg2, arg3, arg1)
      m.assertEqual(result, result2)

      result = obj.mockMethod(arg3, arg2, arg1)
      m.assertEqual(result, result3)

      m.assertMocks()
      isFail = m.currentResult.isFail

      m.currentResult.Reset()
      m.assertFalse(isFail)

    end function

    @it("multi test, multi params with other expects - fail others")
    function _()
      obj = {}
      arg1 = "arg1"
      arg2 = "arg2"
      arg3 = "arg3"
      result1 = 1
      result2 = 2
      result3 = 3

      m.expectOnce(obj, "anotherMockMethod", ["not passed"], "another", true)
      m.expectOnce(obj, "anotherMockMethod2", [1, 2, 3], "another2", true)
      m.expectOnce(obj, "mockMethod", [arg1, arg2, arg3], result1, true)
      m.expectOnce(obj, "mockMethod", [arg2, arg3, arg1], result2, true)
      m.expectOnce(obj, "mockMethod", [arg3, arg2, arg1], result3, true)

      result = obj.anotherMockMethod()
      m.assertEqual(result, "another")

      result = obj.anotherMockMethod2(1, 2, 3)
      m.assertEqual(result, "another2")

      result = obj.mockMethod(arg1, arg2, arg3)
      m.assertEqual(result, result)

      result = obj.mockMethod(arg2, arg3, arg1)
      m.assertEqual(result, result2)

      result = obj.mockMethod(arg3, arg2, arg1)
      m.assertEqual(result, result3)

      m.assertMocks()
      isFail = m.currentResult.isFail

      m.currentResult.Reset()
      m.assertTrue(isFail)

    end function

    @it("can set up multi expects on same method")
    @params("arg1", "arg2", "arg3")
    @params("arg1", "arg2", "arg3")
    @params("arg1", "arg2", "arg3")
    @params("arg1", "arg2", "arg3")
    @params("arg1", "arg2", "arg3")
    @params("arg1", invalid, "arg3")
    function _(call1, call2, call3)
      obj = {}
      arg1 = "arg1"
      arg2 = "arg2"
      arg3 = "arg3"
      result1 = 1
      result2 = 2
      result3 = 3

      m.expectOnce(obj, "mockMethod", [arg1], result1, true)
      m.expectOnce(obj, "mockMethod", [arg2], result2, true)
      m.expectOnce(obj, "mockMethod", [arg3], result3, true)

      result = obj.mockMethod(call1)
      m.assertEqual(result, result1)

      result = obj.mockMethod(call2)
      m.assertEqual(result, result2)

      result = obj.mockMethod(call2)
      m.assertEqual(result, result3)

      m.assertMocks()
      isFail = m.currentResult.isFail

      m.currentResult.Reset()
      m.assertTrue(isFail)
    end function

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @describe("tests overloaded expectOnce on different objects")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    @it("success")
    function _()
      obj = {}
      obj2 = {}
      arg1 = "arg1"
      arg2 = "arg2"
      arg3 = "arg3"
      result1 = 1
      result2 = 2
      result3 = 3

      m.expectOnce(obj, "mockMethod", [arg1], result1, true)
      m.expectOnce(obj, "mockMethod", [arg2], result2, true)
      m.expectOnce(obj2, "mockMethod", [arg3], result3, true)

      result = obj.mockMethod(arg1)
      m.assertEqual(result, result1)

      result = obj.mockMethod(arg2)
      m.assertEqual(result, result2)

      result = obj2.mockMethod(arg3)
      m.assertEqual(result, result3)

      m.assertMocks()
      isFail = m.currentResult.isFail

      m.currentResult.Reset()
      m.assertFalse(isFail)

    end function

    @it("fail to match")
    function _()
      obj = {}
      obj2 = {}
      arg1 = "arg1"
      arg2 = "arg2"
      arg3 = "arg3"
      result1 = 1
      result2 = 2
      result3 = 3

      m.expectOnce(obj, "mockMethod", [arg1], result1, true)
      m.expectOnce(obj, "mockMethod", [arg2], result2, true)
      m.expectOnce(obj2, "mockMethod", [arg3], result3, true)

      result = obj.mockMethod(arg1)
      m.assertEqual(result, result1)

      result = obj.mockMethod(arg2)
      m.assertEqual(result, result2)

      result = obj2.mockMethod(arg3)
      m.assertEqual(result, result3)

      m.assertMocks()
      isFail = m.currentResult.isFail

      m.currentResult.Reset()
      m.assertFalse(isFail)

    end function

    'ASSERTIONS TO WRITE TESTS FOR!

    'This is coming soon!

    '    AssertEqual
    '    AssertLike
    '    AssertNotEqual
    '    AssertInvalid
    '    AssertNotInvalid
    '    AssertAAHasKey
    '    AssertAANotHasKey
    '    AssertAAHasKeys
    '    AssertAANotHasKeys
    '    AssertArrayNotContains
    '    AssertArrayContainsSubset
    '    AssertArrayNotContainsSubsetet
    '    AssertArrayCount
    '    AssertArrayNotCount
    '    AssertArrayContainsOnly
    '    AssertType
    '    AssertSubType
    '
    '    'Node extensions
    '    AssertNodeCount
    '    AssertNodeNotCount
    '    AssertNodeEmpty
    '    AssertNodeNotEmpty
    '    AssertNodeContains
    '    AssertNodeNotContains
    '    AssertNodeContainsFields
    '    AssertNodeNotContainsFields

    '    AssertArray
    '    AssertAAContainsSubset
    '
    '    'Mocking and stubbing
    '    AssertMocks
    '    MockFail
  end class
end namespace