namespace tests

  @suite
  class Common extends Rooibos.BaseTestSuite
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @describe("eqArray")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    @it("compares arrays")
    @params(invalid, [], false)
    @params([], invalid, false)
    @params(invalid, invalid, false)
    @params(["one", "three"], [], false)
    @params([], ["one", "three"], false)
    @params([], [], true)
    @params(["one", "two", "three"], ["one", "three"], false)
    @params(["one", "two", "three"], ["one", "two", "three"], true)
    @params([1, 2, 3], ["one", "two", "three"], false)
    @params([1, 2, 3], [1, 2, 3], true)
    @params([1, invalid, "3"], [1, invalid, "3"], true)
    @params([3, 2, 1], [1, 2, 3], false)
    function _(values, values2, expected)

      result = Rooibos.Common.eqArray(values, values2)
      m.assertEqual(result, expected)

    end function

  end class
end namespace