
namespace tests

  @noEarlyExit
  @suite
  class ExpectTests extends rooibos.BaseTestSuite

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    '+  Helper
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    private function assertRunningTestIsFailed()
      m.isAutoAssertingMocks = false
      m.assertMocks()

      isFail = m.currentResult.isFail
      m.currentResult.Reset()
      m.cleanMocks()
      m.assertTrue(isFail)
    end function

    private function assertRunningTestIsPassed()
      m.isAutoAssertingMocks = false
      m.assertMocks()

      isFail = m.currentResult.isFail
      m.currentResult.Reset()
      m.cleanMocks()
      m.assertFalse(isFail)
    end function

    @describe("expectonce bug")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    @it("tests bug with expectOnce not matching values")
    @params([52], true)
    @params(invalid, false)
    @params([invalid], true)
    @params(["42"], true)
    @params([42], false)
    function _(expectedValue, expectMockFail)
      obj = {
        foo: function(arg0) : return arg0 : end function
      }

      m.ExpectOnce(obj, "foo", expectedValue)
      obj.foo(42)
      m.isAutoAssertingMocks = false
      m.assertMocks()

      isFail = m.currentResult.isFail
      m.currentResult.Reset()
      m.CleanMocks()
      m.assertEqual(isFail, expectMockFail)
    end function


    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @describe("tests mock count limit")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    @it("mock count limit at least 25")
    function _()

      instance = {}

      mockCountLimit = 25
      for i = 1 to mockCountLimit
        keyName = StrI(i).trim()
        instance[keyName] = function(arg0)
          return arg0
        end function

        expectedArg = "a"
        expectedReturnValue = "b"
        m.expectOnce(instance, keyName, [expectedArg], [expectedReturnValue])

        instance[keyName](expectedArg)
      end for

    end function

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @describe("expectCalled regular functions")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    @it("simple")
    function _()
      item = { "id": "node" }
      m.expectCalled(item.getText(), "test")
      m.assertEqual(item.getText(), "test")
    end function

    @it("expected param")
    function _()
      item = { "id": "node" }
      m.expectCalled(item.getText("expected"), "test")
      m.assertEqual(item.getText("expected"), "test")

      m.assertRunningTestIsPassed()
    end function

    @it("not matching on param")
    function _()
      item = { "id": "node" }
      m.expectCalled(item.getText("expected"), "test")

      m.assertEqual(item.getText("not expected"), "test")

      m.assertRunningTestIsFailed()
    end function

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @describe("expectCalled function pointers")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    @it("supports function pointer - therefore ignoring the params")
    function _()
      item = { "id": "node" }
      m.expectCalled(item.getText, "test")

      m.assertEqual(item.getText("any text"), "test")

      m.assertRunningTestIsPassed()
    end function

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @only
    @describe("expectCalled callFunc functions")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    @it("simple")
    function _()
      item = { "id": "node" }
      m.expectCalled(item@.getText(), "test")
      m.assertEqual(item@.getText(), "test")
    end function

    @it("expected param")
    function _()
      item = { "id": "node" }
      m.expectCalled(item@.getText("expected"), "test")
      m.assertEqual(item@.getText("expected"), "test")

      m.assertRunningTestIsPassed()
    end function

    @it("not matching on param")
    function _()
      item = { "id": "node" }
      m.expectCalled(item@.getText("expected"), "test")

      m.assertEqual(item@.getText("not expected"), "test")

      m.assertRunningTestIsFailed()
    end function

  end class

end namespace