
namespace tests

  @noEarlyExit
  @suite
  class ExpectTests extends Rooibos.BaseTestSuite

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @describe("expectonce bug")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    @it("tests bug with expectOnce not matching values")
    @params([52], true)
    @params(invalid, false)
    @params([invalid], true)
    @params(["42"], true)
    @params([42], false)
    function _(expectedValue, expectMockFail)
      obj = {
        foo: function(arg0) : return arg0 : end function
      }

      m.ExpectOnce(obj, "foo", expectedValue)
      obj.foo(42)
      m.isAutoAssertingMocks = false
      m.assertMocks()

      isFail = m.currentResult.isFail
      m.currentResult.Reset()
      m.CleanMocks()
      m.assertEqual(isFail, expectMockFail)
    end function


    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @describe("tests mock count limit")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    @it("mock count limit at least 25")
    function _()

      interface = {}

      mockCountLimit = 25
      for i = 1 to mockCountLimit
        keyName = StrI(i).trim()
        interface[keyName] = function(arg0) : return arg0 : end function

        expectedArg = "a"
        expectedReturnValue = "b"
        m.ExpectOnce(interface, keyName, [expectedArg], [expectedReturnValue])

        interface[keyName](expectedArg)
      end for

    end function
  end class

end namespace