namespace Tests
  'ADD '@Only ON NEXT LINE TO TEST
  '@TestSuite [RBSA] Rooibos before after tests
  class OnlyOnGroups extends Rooibos.BaseTestSuite
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    '@It tests one
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    '@Test it one
    function it_test_one() as void
      m.assertTrue(true)
    end function

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    '@It tests two
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    '@Test it two
    function it_test_two() as void
      m.assertTrue(true)
    end function

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    'ADD '@Only ON NEXT LINE TO TEST
    '@It tests three
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    '@Test it three
    function it_test_three() as void
      m.assertTrue(true)
    end function
  end class
end namespace