namespace Tests
  'ADD '@Only ON NEXT LINE TO TEST
  @TestSuite()
  class OnlyOnGroups extends Rooibos.BaseTestSuite
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @It("tests one")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    @Test
    function it_test_one() as void
      m.assertTrue(true)
    end function

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @It("tests two")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    @Test
    function it_test_two() as void
      m.assertTrue(true)
    end function

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    'ADD '@Only ON NEXT LINE TO TEST
    @It("tests three")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    @Test
    function it_test_three() as void
      m.assertTrue(true)
    end function
  end class
end namespace