namespace tests

  @suite
  @strict
  class VerifyBeforeEachAfterEach extends Rooibos.BaseTestSuite

    private beforeEachValue
    protected override function setup()
      ? "!!! Setup"
    end function

    protected override function tearDown()
      ? "!!! TearDown"
    end function

    protected override function beforeEach()
      ? "!!! Before"
      m.beforeEachValue = 1
    end function

    protected override function afterEach()
      ? "!!! After"
    end function

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @describe("group 1")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    @it("1")
    function _()
      m.assertEqual(m.beforeEachValue, 1)
    end function

    @it("2")
    function _()
      m.assertEqual(m.beforeEachValue, 1)
    end function

    @it("3")
    @params("a")
    @params("b")
    @params("c")
    function _(values)
      m.assertEqual(m.beforeEachValue, 1)
    end function

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @describe("group 2")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    @beforeEach
    function g2_be()
      m.beforeEachValue = 2
      ? "!!! Before GROUP 2"
    end function

    @afterEach
    function g2_ae()
      ? "!!! After GROUP 2"
    end function

    @it("1 ")
    function _()
      m.assertEqual(m.beforeEachValue, 2)
    end function

    @it("2")
    function _()
      m.assertEqual(m.beforeEachValue, 2)
    end function

    @it("3")
    @params("a")
    @params("b")
    @params("c")
    function _(values)
      m.assertEqual(m.beforeEachValue, 2)
    end function

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @describe("group 3")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    @it("1 ")
    function _()
      m.assertEqual(m.beforeEachValue, 1)
    end function

    @it("2")
    function _()
      m.assertEqual(m.beforeEachValue, 1)
    end function

    @it("3")
    @params("a")
    @params("b")
    @params("c")
    function _(values)
      m.assertEqual(m.beforeEachValue, 1)
    end function

  end class
end namespace
