
    '***************************************************
    ' This file is generated by rooibos. DO NOT EDIT. RTM please :)
    ' ***************************************************
    

    '***************************************************
    'Function maps
    '***************************************************
    function RBSFM_getFunctionsForFile(filename)
  map = {
    "NodeExampleTests":RBSFM_getFunctions_NodeExampleTests 
    "VideoModuleTests":RBSFM_getFunctions_VideoModuleTests 
    "rooibosDist":RBSFM_getFunctions_rooibosDist 
    "rooibosFunctionMap":RBSFM_getFunctions_rooibosFunctionMap 
    "test_LegacyIntegration":RBSFM_getFunctions_test_LegacyIntegration 
  } 
  return map[filename]
end function

function RBSFM_getFunctions_NodeExampleTests()
  return {
    "NET_setup":NET_setup 
    "NET_BeforeEach":NET_BeforeEach 
    "NET__HelloFromNode_simple":NET__HelloFromNode_simple 
    "NET__HelloFromNode_params":NET__HelloFromNode_params 
  } 

end function

function RBSFM_getFunctions_VideoModuleTests()
  return {
    "VMT_BeforeEach":VMT_BeforeEach 
    "VMT__constructor_basic":VMT__constructor_basic 
    "VMT__getVideos_basic":VMT__getVideos_basic 
    "VMT__getVideosRealExample_basic":VMT__getVideosRealExample_basic 
  } 

end function

function RBSFM_getFunctions_rooibosDist()
  return {
    "Rooibos__Init":Rooibos__Init 
    "BaseTestSuite":BaseTestSuite 
    "RBS_BTS_AddTest":RBS_BTS_AddTest 
    "RBS_BTS_CreateTest":RBS_BTS_CreateTest 
    "RBS_BTS_Fail":RBS_BTS_Fail 
    "RBS_BTS_GetLegacyCompatibleReturnValue":RBS_BTS_GetLegacyCompatibleReturnValue 
    "RBS_BTS_AssertFalse":RBS_BTS_AssertFalse 
    "RBS_BTS_AssertTrue":RBS_BTS_AssertTrue 
    "RBS_BTS_AssertEqual":RBS_BTS_AssertEqual 
    "RBS_BTS_AssertLike":RBS_BTS_AssertLike 
    "RBS_BTS_AssertNotEqual":RBS_BTS_AssertNotEqual 
    "RBS_BTS_AssertInvalid":RBS_BTS_AssertInvalid 
    "RBS_BTS_AssertNotInvalid":RBS_BTS_AssertNotInvalid 
    "RBS_BTS_AssertAAHasKey":RBS_BTS_AssertAAHasKey 
    "RBS_BTS_AssertAANotHasKey":RBS_BTS_AssertAANotHasKey 
    "RBS_BTS_AssertAAHasKeys":RBS_BTS_AssertAAHasKeys 
    "RBS_BTS_AssertAANotHasKeys":RBS_BTS_AssertAANotHasKeys 
    "RBS_BTS_AssertArrayContains":RBS_BTS_AssertArrayContains 
    "RBS_BTS_AssertArrayContainsAAs":RBS_BTS_AssertArrayContainsAAs 
    "RBS_BTS_AssertArrayNotContains":RBS_BTS_AssertArrayNotContains 
    "RBS_BTS_AssertArrayContainsSubset":RBS_BTS_AssertArrayContainsSubset 
    "RBS_BTS_AssertArrayNotContainsSubset":RBS_BTS_AssertArrayNotContainsSubset 
    "RBS_BTS_AssertArrayCount":RBS_BTS_AssertArrayCount 
    "RBS_BTS_AssertArrayNotCount":RBS_BTS_AssertArrayNotCount 
    "RBS_BTS_AssertEmpty":RBS_BTS_AssertEmpty 
    "RBS_BTS_AssertNotEmpty":RBS_BTS_AssertNotEmpty 
    "RBS_BTS_AssertArrayContainsOnlyValuesOfType":RBS_BTS_AssertArrayContainsOnlyValuesOfType 
    "RBS_CMN_GetIsTypeFunction":RBS_CMN_GetIsTypeFunction 
    "RBS_BTS_AssertType":RBS_BTS_AssertType 
    "RBS_BTS_AssertSubType":RBS_BTS_AssertSubType 
    "RBS_BTS_EqValues":RBS_BTS_EqValues 
    "RBS_BTS_EqAssocArray":RBS_BTS_EqAssocArray 
    "RBS_BTS_EqArray":RBS_BTS_EqArray 
    "RBS_BTS_AssertNodeCount":RBS_BTS_AssertNodeCount 
    "RBS_BTS_AssertNodeNotCount":RBS_BTS_AssertNodeNotCount 
    "RBS_BTS_AssertNodeEmpty":RBS_BTS_AssertNodeEmpty 
    "RBS_BTS_AssertNodeNotEmpty":RBS_BTS_AssertNodeNotEmpty 
    "RBS_BTS_AssertNodeContains":RBS_BTS_AssertNodeContains 
    "RBS_BTS_AssertNodeContainsOnly":RBS_BTS_AssertNodeContainsOnly 
    "RBS_BTS_AssertNodeNotContains":RBS_BTS_AssertNodeNotContains 
    "RBS_BTS_AssertNodeContainsFields":RBS_BTS_AssertNodeContainsFields 
    "RBS_BTS_AssertNodeNotContainsFields":RBS_BTS_AssertNodeNotContainsFields 
    "RBS_BTS_AssertAAContainsSubset":RBS_BTS_AssertAAContainsSubset 
    "RBS_BTS_Stub":RBS_BTS_Stub 
    "RBS_BTS_ExpectOnce":RBS_BTS_ExpectOnce 
    "RBS_BTS_ExpectOnceOrNone":RBS_BTS_ExpectOnceOrNone 
    "RBS_BTS_ExpectNone":RBS_BTS_ExpectNone 
    "RBS_BTS_Expect":RBS_BTS_Expect 
    "RBS_BTS_Mock":RBS_BTS_Mock 
    "RBS_BTS_CreateFake":RBS_BTS_CreateFake 
    "RBS_BTS_AssertMocks":RBS_BTS_AssertMocks 
    "RBS_CMN_IsXmlElement":RBS_CMN_IsXmlElement 
    "RBS_CMN_IsFunction":RBS_CMN_IsFunction 
    "RBS_CMN_GetFunction":RBS_CMN_GetFunction 
    "RBS_CMN_GetFunctionBruteForce":RBS_CMN_GetFunctionBruteForce 
    "RBS_CMN_IsBoolean":RBS_CMN_IsBoolean 
    "RBS_CMN_IsInteger":RBS_CMN_IsInteger 
    "RBS_CMN_IsFloat":RBS_CMN_IsFloat 
    "RBS_CMN_IsDouble":RBS_CMN_IsDouble 
    "RBS_CMN_IsLongInteger":RBS_CMN_IsLongInteger 
    "RBS_CMN_IsNumber":RBS_CMN_IsNumber 
    "RBS_CMN_IsList":RBS_CMN_IsList 
    "RBS_CMN_IsArray":RBS_CMN_IsArray 
    "RBS_CMN_IsAssociativeArray":RBS_CMN_IsAssociativeArray 
    "RBS_CMN_IsSGNode":RBS_CMN_IsSGNode 
    "RBS_CMN_IsString":RBS_CMN_IsString 
    "RBS_CMN_IsNotEmptyString":RBS_CMN_IsNotEmptyString 
    "RBS_CMN_IsDateTime":RBS_CMN_IsDateTime 
    "RBS_CMN_IsValid":RBS_CMN_IsValid 
    "RBS_CMN_IsUndefined":RBS_CMN_IsUndefined 
    "RBS_CMN_ValidStr":RBS_CMN_ValidStr 
    "RBS_CMN_AsString":RBS_CMN_AsString 
    "RBS_CMN_AsInteger":RBS_CMN_AsInteger 
    "RBS_CMN_AsLongInteger":RBS_CMN_AsLongInteger 
    "RBS_CMN_AsFloat":RBS_CMN_AsFloat 
    "RBS_CMN_AsDouble":RBS_CMN_AsDouble 
    "RBS_CMN_AsBoolean":RBS_CMN_AsBoolean 
    "RBS_CMN_AsArray":RBS_CMN_AsArray 
    "RBS_CMN_IsNullOrEmpty":RBS_CMN_IsNullOrEmpty 
    "RBS_CMN_FindElementIndexInArray":RBS_CMN_FindElementIndexInArray 
    "RBS_CMN_ArrayContains":RBS_CMN_ArrayContains 
    "RBS_CMN_FindElementIndexInNode":RBS_CMN_FindElementIndexInNode 
    "RBS_CMN_NodeContains":RBS_CMN_NodeContains 
    "RBS_ItG_GetTestCases":RBS_ItG_GetTestCases 
    "RBS_ItG_GetRunnableTestSuite":RBS_ItG_GetRunnableTestSuite 
    "ItemGenerator":ItemGenerator 
    "RBS_IG_GetItem":RBS_IG_GetItem 
    "RBS_IG_GetAssocArray":RBS_IG_GetAssocArray 
    "RBS_IG_GetArray":RBS_IG_GetArray 
    "RBS_IG_GetSimpleType":RBS_IG_GetSimpleType 
    "RBS_IG_GetBoolean":RBS_IG_GetBoolean 
    "RBS_IG_GetInteger":RBS_IG_GetInteger 
    "RBS_IG_GetFloat":RBS_IG_GetFloat 
    "RBS_IG_GetString":RBS_IG_GetString 
    "UnitTestRuntimeConfig":UnitTestRuntimeConfig 
    "RBS_CreateSuites":RBS_CreateSuites 
    "RBS_STATS_CreateTotalStatistic":RBS_STATS_CreateTotalStatistic 
    "RBS_STATS_MergeTotalStatistic":RBS_STATS_MergeTotalStatistic 
    "RBS_STATS_CreateSuiteStatistic":RBS_STATS_CreateSuiteStatistic 
    "RBS_STATS_CreateTestStatistic":RBS_STATS_CreateTestStatistic 
    "RBS_STATS_AppendTestStatistic":RBS_STATS_AppendTestStatistic 
    "RBS_STATS_AppendSuiteStatistic":RBS_STATS_AppendSuiteStatistic 
    "UnitTestCase":UnitTestCase 
    "RBS_TC_AddAssertLine":RBS_TC_AddAssertLine 
    "RBS_TC_GetAssertLine":RBS_TC_GetAssertLine 
    "Logger":Logger 
    "RBS_LOGGER_PrintStatistic":RBS_LOGGER_PrintStatistic 
    "RBS_LOGGER_PrintSuiteStatistic":RBS_LOGGER_PrintSuiteStatistic 
    "RBS_LOGGER_PrintTestStatistic":RBS_LOGGER_PrintTestStatistic 
    "RBS_LOGGER_FillText":RBS_LOGGER_FillText 
    "RBS_LOGGER_PrintStart":RBS_LOGGER_PrintStart 
    "RBS_LOGGER_PrintEnd":RBS_LOGGER_PrintEnd 
    "RBS_LOGGER_PrintSuiteSetUp":RBS_LOGGER_PrintSuiteSetUp 
    "RBS_LOGGER_PrintMetaSuiteStart":RBS_LOGGER_PrintMetaSuiteStart 
    "RBS_LOGGER_PrintSuiteStart":RBS_LOGGER_PrintSuiteStart 
    "RBS_LOGGER_PrintSuiteTearDown":RBS_LOGGER_PrintSuiteTearDown 
    "RBS_LOGGER_PrintTestSetUp":RBS_LOGGER_PrintTestSetUp 
    "RBS_LOGGER_PrintTestTearDown":RBS_LOGGER_PrintTestTearDown 
    "UnitTestResult":UnitTestResult 
    "RBS_TRes_Reset":RBS_TRes_Reset 
    "RBS_TRes_AddResult":RBS_TRes_AddResult 
    "RBS_TRes_GetResult":RBS_TRes_GetResult 
    "RBS_TR_TestRunner":RBS_TR_TestRunner 
    "RBS_TR_Run":RBS_TR_Run 
    "RBS_RT_RunItGroups":RBS_RT_RunItGroups 
    "RBS_RT_RunTestCases":RBS_RT_RunTestCases 
    "RBS_TR_SendHomeKeypress":RBS_TR_SendHomeKeypress 
    "Rooibos_RunNodeTests":Rooibos_RunNodeTests 
    "Rooibos_CreateTestNode":Rooibos_CreateTestNode 
  } 

end function

function RBSFM_getFunctions_rooibosFunctionMap()
  return {
    "RBSFM_getFunctions_NodeExampleTests":RBSFM_getFunctions_NodeExampleTests 
    "RBSFM_getFunctions_VideoModuleTests":RBSFM_getFunctions_VideoModuleTests 
    "RBSFM_getFunctions_rooibosDist":RBSFM_getFunctions_rooibosDist 
    "RBSFM_getFunctions_test_LegacyIntegration":RBSFM_getFunctions_test_LegacyIntegration 
    "RBSFM_getFilenames":RBSFM_getFilenames 
  } 

end function

function RBSFM_getFunctions_test_LegacyIntegration()
  return {
    "testSuite_LegacyIntegration":testSuite_LegacyIntegration 
    "LegacyIntegrationTestSuite_SetUp":LegacyIntegrationTestSuite_SetUp 
    "testCase_LegacyIntegration_simpleResult":testCase_LegacyIntegration_simpleResult 
    "testCase_LegacyIntegration_multipleAsserts":testCase_LegacyIntegration_multipleAsserts 
  } 

end function

function RBSFM_getFilenames()
  return [
    "NodeExampleTests", 
    "VideoModuleTests", 
    "rooibosDist", 
    "rooibosFunctionMap", 
    "test_LegacyIntegration", 
  ] 
end function



    '***************************************************
    ' Unit test suites defitintions
    '***************************************************
    

    function RBSFM_getTestSuitesForProject()
        return [
        
{
      name: "[NET] Node Example Tests"
      filePath: "pkg:/source/tests/NodeExampleTests.brs"
      valid: true
      hasFailures: false
      hasSoloTests: false
      hasIgnoredTests: false
      hasSoloGroups: false
      isSolo: false
      isIgnored: false
      itGroups: [
      {
        testCases: [
        {
          isSolo: false
          funcName: "NET__HelloFromNode_simple"
          isIgnored: false
          isParamTest: false
          name: "HelloFromNode"
          lineNumber: 19
          paramLineNumber: 0
          assertIndex: 1
          assertLineNumberMap: {"0":21}
          rawParams: []
          paramTestIndex: 0
          expectedNumberOfParams: 0
          isParamsValid: true
        },
        {
          isSolo: false
          funcName: "NET__HelloFromNode_params"
          isIgnored: false
          isParamTest: true
          name: "HelloFromNode with params0"
          lineNumber: 31
          paramLineNumber: 25
          assertIndex: 1
          assertLineNumberMap: {"0":33}
          rawParams: ["jon",40]
          paramTestIndex: 0
          expectedNumberOfParams: 2
          isParamsValid: true
        },
        {
          isSolo: false
          funcName: "NET__HelloFromNode_params"
          isIgnored: false
          isParamTest: true
          name: "HelloFromNode with params1"
          lineNumber: 31
          paramLineNumber: 26
          assertIndex: 1
          assertLineNumberMap: {"0":33}
          rawParams: ["ringo",23]
          paramTestIndex: 1
          expectedNumberOfParams: 2
          isParamsValid: true
        },
        {
          isSolo: false
          funcName: "NET__HelloFromNode_params"
          isIgnored: false
          isParamTest: true
          name: "HelloFromNode with params2"
          lineNumber: 31
          paramLineNumber: 27
          assertIndex: 1
          assertLineNumberMap: {"0":33}
          rawParams: ["ringo",50]
          paramTestIndex: 2
          expectedNumberOfParams: 2
          isParamsValid: true
        },
        {
          isSolo: false
          funcName: "NET__HelloFromNode_params"
          isIgnored: false
          isParamTest: true
          name: "HelloFromNode with params3"
          lineNumber: 31
          paramLineNumber: 28
          assertIndex: 1
          assertLineNumberMap: {"0":33}
          rawParams: ["ringo",24]
          paramTestIndex: 3
          expectedNumberOfParams: 2
          isParamsValid: true
        },
        {
          isSolo: false
          funcName: "NET__HelloFromNode_params"
          isIgnored: false
          isParamTest: true
          name: "HelloFromNode with params4"
          lineNumber: 31
          paramLineNumber: 29
          assertIndex: 1
          assertLineNumberMap: {"0":33}
          rawParams: ["george",40]
          paramTestIndex: 4
          expectedNumberOfParams: 2
          isParamsValid: true
        },
        {
          isSolo: false
          funcName: "NET__HelloFromNode_params"
          isIgnored: false
          isParamTest: true
          name: "HelloFromNode with params5"
          lineNumber: 31
          paramLineNumber: 30
          assertIndex: 1
          assertLineNumberMap: {"0":33}
          rawParams: ["paul",50]
          paramTestIndex: 5
          expectedNumberOfParams: 2
          isParamsValid: true
        }]
        ignoredTestCases: []
        soloTestCases: []
        filename: "NodeExampleTests"
        setupFunctionName: "NET_setup"
        tearDownFunctionName: ""
        beforeEachFunctionName: "NET_BeforeEach"
        afterEachFunctionName: ""
        isSolo: false
        isIgnored: false
        hasSoloTests: false
        name: "tests methods present on the node"
      }]
      setupFunctionName: "NET_setup"
      tearDownFunctionName: ""
      isNodeTest: true
      nodeTestFileName: "NodeExampleTests"
      beforeEachFunctionName: ""
      afterEachFunctionName: ""
    },

{
      name: "[VMT] VideoModuleTests"
      filePath: "pkg:/source/tests/VideoModuleTests.brs"
      valid: true
      hasFailures: false
      hasSoloTests: false
      hasIgnoredTests: false
      hasSoloGroups: false
      isSolo: false
      isIgnored: false
      itGroups: [
      {
        testCases: [
        {
          isSolo: false
          funcName: "VMT__constructor_basic"
          isIgnored: false
          isParamTest: false
          name: "basic constructor values"
          lineNumber: 16
          paramLineNumber: 0
          assertIndex: 2
          assertLineNumberMap: {"0":17,"1":18}
          rawParams: []
          paramTestIndex: 0
          expectedNumberOfParams: 0
          isParamsValid: true
        }]
        ignoredTestCases: []
        soloTestCases: []
        filename: "VideoModuleTests"
        setupFunctionName: ""
        tearDownFunctionName: ""
        beforeEachFunctionName: "VMT_BeforeEach"
        afterEachFunctionName: ""
        isSolo: false
        isIgnored: false
        hasSoloTests: false
        name: "tests constructor"
      },
      {
        testCases: [
        {
          isSolo: false
          funcName: "VMT__getVideos_basic"
          isIgnored: false
          isParamTest: true
          name: "basic test0"
          lineNumber: 30
          paramLineNumber: 27
          assertIndex: 3
          assertLineNumberMap: {"0":33,"1":34,"2":41}
          rawParams: [3,"mp4",["video_0","video_1","video_2"]]
          paramTestIndex: 0
          expectedNumberOfParams: 3
          isParamsValid: true
        },
        {
          isSolo: false
          funcName: "VMT__getVideos_basic"
          isIgnored: false
          isParamTest: true
          name: "basic test1"
          lineNumber: 30
          paramLineNumber: 28
          assertIndex: 3
          assertLineNumberMap: {"0":33,"1":34,"2":41}
          rawParams: [2,"mpg",["video_0","video_1"]]
          paramTestIndex: 1
          expectedNumberOfParams: 3
          isParamsValid: true
        },
        {
          isSolo: false
          funcName: "VMT__getVideos_basic"
          isIgnored: false
          isParamTest: true
          name: "basic test2"
          lineNumber: 30
          paramLineNumber: 29
          assertIndex: 3
          assertLineNumberMap: {"0":33,"1":34,"2":41}
          rawParams: [1,"vp8",["video_0"]]
          paramTestIndex: 2
          expectedNumberOfParams: 3
          isParamsValid: true
        }]
        ignoredTestCases: []
        soloTestCases: []
        filename: "VideoModuleTests"
        setupFunctionName: ""
        tearDownFunctionName: ""
        beforeEachFunctionName: "VMT_BeforeEach"
        afterEachFunctionName: ""
        isSolo: false
        isIgnored: false
        hasSoloTests: false
        name: "tests getVideos"
      },
      {
        testCases: [
        {
          isSolo: false
          funcName: "VMT__getVideosRealExample_basic"
          isIgnored: false
          isParamTest: true
          name: "basic test0"
          lineNumber: 51
          paramLineNumber: 49
          assertIndex: 1
          assertLineNumberMap: {"0":56}
          rawParams: ["mp4",["a","b","c"]]
          paramTestIndex: 0
          expectedNumberOfParams: 2
          isParamsValid: true
        },
        {
          isSolo: false
          funcName: "VMT__getVideosRealExample_basic"
          isIgnored: false
          isParamTest: true
          name: "basic test1"
          lineNumber: 51
          paramLineNumber: 50
          assertIndex: 1
          assertLineNumberMap: {"0":56}
          rawParams: ["mp3",["a","b","c","d","e"]]
          paramTestIndex: 1
          expectedNumberOfParams: 2
          isParamsValid: true
        }]
        ignoredTestCases: []
        soloTestCases: []
        filename: "VideoModuleTests"
        setupFunctionName: ""
        tearDownFunctionName: ""
        beforeEachFunctionName: "VMT_BeforeEach"
        afterEachFunctionName: ""
        isSolo: false
        isIgnored: false
        hasSoloTests: false
        name: "tests getVideosRealExample"
      }]
      setupFunctionName: ""
      tearDownFunctionName: ""
      isNodeTest: false
      nodeTestFileName: ""
      beforeEachFunctionName: "VMT_BeforeEach"
      afterEachFunctionName: ""
    },

      ]
    end function



    '***************************************************
    ' This file is generated by rooibos. DO NOT EDIT. RTM please :)
    ' ***************************************************
    
