import "pkg:/source/roku_modules/log/LogMixin.brs"

function Init() as void
  createObject("roSGNode", "TrackerTask")
  m.global.addFields({"isFocusLocked": false})
  m.top.rLog = log_initializeLog()
  m.top.rLog.logLevel = 5
  m.top.rLog.excludeFilters = ["TabController"]  
  log_registerLogger("MainScene")
  log_logInfo("init")
end function
  
  ' /**
  '  * @member begin
  '  * @memberof module:MainScene
  '  * @instance
  '  * @description This would be called when all initial data is loaded. The app would show a loading spinner and loading background until this point
  '  * @param {paramType} paramDescription
  '  * @returns {returnType} returnDescription
  '  */
function begin(args = invalid)
  log_logInfo("begin")
  initializeIOC()
  m.modelLocator.appArgs = args

  log_logInfo("starting the bootstrap task to orchestrate our app init/loading tasks")
  ' my apps have a task here that manages the various app initialization activities
  ' m.bootstrapSequence = crateObject("roSGNode", "bootstrapTasks")
  ' m.loadingSequence.observeField("isComplete", "onIsBootstrapTasksComplete")
  ' let's just pretend it did it for now
  onIsBootstrapTasksComplete()
end function

function onIsBootstrapTasksComplete()
  log_logInfo("boot strap is complete - showing main screen")

  m.top.appController = createObject("roSGNode", "AppController")
  m.global.addFields({"appController": m.top.appController})
  m.modelLocator.appController = m.top.appController
  m.top.appendChild(m.top.appController)
  m.top.appController@._initialize()
  m.top.appController.setFocus(true)
end function

function initializeIOC()
  log_logInfo("initializing the IOD container")
  'we use a simple modelLocator for now
  'later we'd load our IOC container here
  m.modelLocator = createObject("roSGNode", "ModelLocator")
  m.top._modelLocator = m.modelLocator
  m.global.addFields({"modelLocator": m.modelLocator})
end function